"""empty message

Revision ID: 00e201761820
Revises: 9b8de01af7fb
Create Date: 2021-12-20 18:07:36.288938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e201761820'
down_revision = '9b8de01af7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=11), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
