"""empty message

Revision ID: 7472b3fa9ae9
Revises: be00d7b672b9
Create Date: 2021-12-04 16:53:16.812021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7472b3fa9ae9'
down_revision = 'be00d7b672b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorysong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musicType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songWriter', sa.String(length=100), nullable=False),
    sa.Column('songName', sa.String(length=120), nullable=False),
    sa.Column('songDescription', sa.Text(), nullable=True),
    sa.Column('songLink', sa.String(length=250), nullable=False),
    sa.Column('songCategory', sa.Integer(), nullable=True),
    sa.Column('songYear', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['songCategory'], ['categorysong.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('categorysong')
    # ### end Alembic commands ###
