"""empty message

Revision ID: 9b8de01af7fb
Revises: 7472b3fa9ae9
Create Date: 2021-12-04 19:20:23.635483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8de01af7fb'
down_revision = '7472b3fa9ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('songDuration', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('songDuration')

    # ### end Alembic commands ###
